add rating form functionality, still need tests

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -17,15 +17,18 @@ if [[ "$?" == 1 ]]; then
   exit 1
 fi
 
-for FILE in $STAGED_FILES
-do
-  flake8 "$FILE"
-
-  if [[ "$?" == 0 ]]; then
-    echo "\t\033[32mflake8 Passed: $FILE\033[0m"
+for FILE in $STAGED_FILES; do
+  if [[ "$FILE" =~ "migrations" ]]; then
+    echo "\t\033[32mSkipping migration file: $FILE\033[0m"
   else
-    echo "\t\033[41mflake8 Failed: $FILE\033[0m"
-    PASS=false
+      flake8 "$FILE"
+
+      if [[ "$?" == 0 ]]; then
+        echo "\t\033[32mflake8 Passed: $FILE\033[0m"
+      else
+        echo "\t\033[41mflake8 Failed: $FILE\033[0m"
+        PASS=false
+      fi
   fi
 done
 
